name: prepare2travel
description: "Helps make travels easier"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0-152.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  intl: any
  hive_flutter: ^1.1.0
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  talker_flutter: ^3.5.7
  talker_dio_logger: ^2.3.4
  talker_bloc_logger: ^2.3.3
  shimmer: ^3.0.0
  csc_picker: ^0.2.7
  community_material_icon: ^5.9.55
  geocoding: ^2.1.1 #TODO check for usages
  home_widget: ^0.4.1
  firebase_core: ^2.25.0
  firebase_auth: ^4.17.0
  firebase_storage: ^11.6.1
  cloud_firestore: ^4.15.0
  google_sign_in: ^6.2.1
  email_validator: ^2.1.17
  equatable: ^2.0.5
  either_dart: ^1.0.0
  go_router: ^13.1.0
  fluttertoast: ^8.2.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.3
  hive_generator: ^2.0.1
  build_runner:

flutter:
  generate: true
  uses-material-design: true
